export type ProtectedAreaRef = {
	designation: string;
	name: string;
};

export type Municipio = {
	id: string;
	codigo: string;
	nombre: string;
	provincia: string;
	provincia_id_geo?: string;
	provincia_nombre_geo?: string;
	lat: number;
	lon: number;
	population?: number;
	population_men?: number;
	population_women?: number;
	precip_annual_mm: number;
	precip_summer_mm?: number;
	precip_winter_mm?: number;
	precip_seasonality_index?: number;
	aridity_index?: number;
	summer_aridity_index?: number;
	dry_months_count?: number;
	moisture_absolute_score?: number;
	summer_drought_score?: number;
	precip_relative_score?: number;
	precip_moisture_score?: number;
	water_drops_level?: number;
	water_drops_label?: string;
	temp_winter_mean_c: number;
	temp_summer_mean_c: number;
	temp_jan_mean_c: number;
	temp_jul_mean_c: number;
	iso_01h30m: boolean;
	iso_02h00m: boolean;
	iso_02h30m: boolean;
	iso_03h30m: boolean;
	iso_04h00m: boolean;
	travel_bucket: string;
	precip_norm?: number;
	temp_verano_norm?: number;
	temp_invierno_norm?: number;
	accesibilidad_norm?: number;
	forest_pct?: number;
	water_pct?: number;
	artificial_pct?: number;
	naturality_index?: number;
	landcover_diversity?: number;
	forest_norm?: number;
	water_norm?: number;
	artificial_norm?: number;
	naturality_norm?: number;
	diversity_norm?: number;
	river_access_norm?: number;
	river_access_score?: number;
	river_access_class?: string;
	river_nearest_name?: string;
	river_nearest_distance_km?: number;
	river_nearest_confidence?: number;
	river_candidate_count_10km?: number;
	river_method_version?: string;
	protected_areas?: string | ProtectedAreaRef[];
	protected_areas_source?: string;
	climate_block_score?: number;
	access_block_score?: number;
	nature_block_score?: number;
	mixed_score?: number;
	dist_estacion_tren_km?: number;
	dist_parada_bus_km?: number;
	transporte_norm?: number;
	dist_renfe_km?: number;
	renfe_salidas_dia?: number;
	renfe_tipo_servicio?: string;
	servicio_renfe_norm?: number;
	dist_renfe_madrid_km?: number;
	renfe_madrid_active_days?: number;
	renfe_madrid_coverage_pct?: number;
	renfe_madrid_departures_total?: number;
	renfe_madrid_departures_avg_day?: number;
	renfe_madrid_departures_active_day?: number;
	renfe_madrid_departures_p25?: number;
	renfe_madrid_weekend_service?: boolean;
	renfe_madrid_routes_count?: number;
	renfe_madrid_stop_id?: string;
	renfe_madrid_stop_name?: string;
	renfe_madrid_stop_municipality?: string;
	renfe_madrid_stop_province?: string;
	renfe_madrid_connection_type?: string;
	renfe_madrid_service_norm?: number;
	// Transport status derived fields
	has_direct_madrid_service?: boolean;
	has_nearby_station?: boolean;
	nearest_station_distance_km?: number;
	transport_confidence?: 'high' | 'medium' | 'low';
	transport_status?: 'direct_madrid' | 'station_nearby' | 'no_station';
	relieve_norm?: number;
	relieve_score_raw?: number;
	// Grid aggregation (from 2km cells)
	precip_annual_mean?: number;
	temp_winter_mean?: number;
	temp_summer_mean?: number;
	river_access_mean?: number;
	river_access_max?: number;
	river_access_p75?: number;
	pct_cells_river_access_high?: number;
	nearest_good_river_distance?: number;
	natural_cover_mean?: number;
	pct_cells_natural_high?: number;
	isochrone_best?: string;
	isochrone_majority?: string;
	pct_area_inside_2h30?: number;
};

export type MunicipioClimateMonthly = {
	id: string;
	nombre: string;
	provincia: string;
	month: number;
	temp_mean_c: number;
	precip_mm: number;
};

export type DatasetMetadata = {
	dataset_version: string;
	generated_at_utc: string;
	analysis_scope: string;
	climate_source: string;
	climate_reference?: string;
	environment_source?: string;
	climate_period: string;
	aggregation_method: string;
	isochrones_definition: string;
	scoring_method?: string;
	accessibility_normalization_floor?: number;
	scoring_weights?: {
		climate: number;
		accessibility: number;
		nature: number;
	};
};
