export type Municipio = {
	id: string;
	codigo: string;
	nombre: string;
	provincia: string;
	lat: number;
	lon: number;
	population?: number;
	population_men?: number;
	population_women?: number;
	precip_annual_mm: number;
	temp_winter_mean_c: number;
	temp_summer_mean_c: number;
	temp_jan_mean_c: number;
	temp_jul_mean_c: number;
	iso_01h30m: boolean;
	iso_02h00m: boolean;
	iso_02h30m: boolean;
	iso_03h30m: boolean;
	iso_04h00m: boolean;
	travel_bucket: string;
	precip_norm?: number;
	temp_verano_norm?: number;
	temp_invierno_norm?: number;
	accesibilidad_norm?: number;
	forest_pct?: number;
	water_pct?: number;
	artificial_pct?: number;
	naturality_index?: number;
	landcover_diversity?: number;
	forest_norm?: number;
	water_norm?: number;
	artificial_norm?: number;
	naturality_norm?: number;
	diversity_norm?: number;
	river_access_norm?: number;
	river_access_score?: number;
	river_access_class?: string;
	river_nearest_name?: string;
	river_nearest_distance_km?: number;
	river_nearest_confidence?: number;
	river_candidate_count_10km?: number;
	river_method_version?: string;
	climate_block_score?: number;
	access_block_score?: number;
	nature_block_score?: number;
	mixed_score?: number;
	dist_estacion_tren_km?: number;
	dist_parada_bus_km?: number;
	transporte_norm?: number;
	dist_renfe_km?: number;
	renfe_salidas_dia?: number;
	renfe_tipo_servicio?: string;
	servicio_renfe_norm?: number;
};

export type MunicipioClimateMonthly = {
	id: string;
	nombre: string;
	provincia: string;
	month: number;
	temp_mean_c: number;
	precip_mm: number;
};

export type DatasetMetadata = {
	dataset_version: string;
	generated_at_utc: string;
	analysis_scope: string;
	climate_source: string;
	environment_source?: string;
	climate_period: string;
	aggregation_method: string;
	isochrones_definition: string;
	scoring_method?: string;
	accessibility_normalization_floor?: number;
	scoring_weights?: {
		climate: number;
		accessibility: number;
		nature: number;
	};
};
